version: "3.7"
services:
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api
      - client
  api:
    container_name: api
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - 5000:5000
  client:
    container_name: client
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - 3000:3000
